### ISSUE TITLE
Doesn't work when the anchor is a normal link

### ISSUE THREAD

**Issue by ghost** [zengabor/zenscroll#20]
It only seems to work when an anchor is only a hash. 

For example, if my anchor is `/our-team/#member_name', clicking on that from a different page is fine, the page changes and the browser automatically scrolls to that point on the page without Zen. But if you click on that link from that page, Zen doesn't work and it automatically snaps to that point.

**Comment by zengabor** [comment]
This is an implementation choice, so this is expected behavior. The anchor must start with # otherwise Zenscroll won't handle it.

Sorry that it isn't working as you would expect it. The reason is simplicity: the current implementation is reliable as it doesn't need to deal with calculating the final destination. Consider links like this: "../../foo/bar/#baz"

**Comment by Finesse** [comment]
@zengabor Browser calculates the final link URL when you get the `href` value:

```html
<a href="../../foo/bar/#baz" id="link">Link</a>
<script>
    console.log(document.getElementById('link').href); // 'https://github.com/zengabor/foo/bar#baz'
</script>
```

So you can compare the link and the document URL safely:

```js
function getURLWithoutAnchor(url) {
    return url.split('#')[0];
}

const currentURL = location.href;
const linkURL = link.href;

if (getURLWithoutAnchor(currentURL) === getURLWithoutAnchor(linkURL)) {
    doScroll();
}
```

Please consider this comment as reopening this issue.

**Comment by zengabor** [comment]
Fair point

**Comment by Finesse** [comment]
@zengabor I updated [my comment](https://github.com/zengabor/zenscroll/issues/20#issuecomment-369473279) with a solution suggestion. Could you please view it?
