### ISSUE TITLE
Back button doesn't scroll to previous location

### ISSUE THREAD

**Issue by xvvvyz** [zengabor/zenscroll#24]
I expected, after clicking on a link, that clicking the back button would return me to the previous location on the page.

Is this feasible? I'd be happy to submit a pull request if it is.

**Comment by zengabor** [comment]
First I wanted to do history handling exactly how you describe it. But then I didn't like how it worked on my site (because I had to hit the back button several times when I wanted to navigate back to a previous page).

This is written in README.md:

> Internal links are intentionally not added to the history to save the users from having to hit the Back button too many times afterwards.

However, now I think you are right. This should be the normal behavior.

**Comment by zengabor** [comment]
Fixed in version 3.3.0
