### ISSUE TITLE
Page Load offset for anchors

### ISSUE THREAD

**Issue by dotnetshadow** [zengabor/zenscroll#35]
Hi there,

Great plugin, 

I noticed when there is a hashtag in the url, you automatically try to go to the anchor tag on the page. I found that the following prevented this from happening

`if (0 <= diff && diff < 9 ) `

I found with my particular page I needed to remove this statement to get it to go to the correct location. I had a fixed header on the page. I know you use a magic number 9 there wonder if that could be configurable?

Also you use `window.scrollTo` compared to `zenscroll.to` is that to keep it inline with the default way the browser handles hashtags?

**Comment by zengabor** [comment]
Can you show me that page so that I can understand how it could be solved?

`9` is just a number for close proximity. Some browsers (on HD screens?) use floating numbers for pixel values, that's why I have to check for a range here.

I use `window.scrollTo()` for quick speed and instant jump because this happens on load.

**Comment by dotnetshadow** [comment]
Hi there, 

The page is this:
https://www.fantasysportsgame.com.au/rules/

I'm using a modified version of your code to exclude the 9 pixel problem so you won't see the issue unless you inject your version of the code in that page
