### ISSUE TITLE
Not Scrolling

### ISSUE THREAD

**Issue by b8ne** [zengabor/zenscroll#38]
Just installed this on a second site, because the first site worked a dream...
Having an issue with non scrolling though.

My setup is 
```
window.noZensmooth = true;
window.zenscroll = require('zenscroll');
```

and calling via `zenscroll.toY(el.offsetTop, 1000);`

Ive debugged the issue down to line 125 of zenscroll.js, where `container.body.scrollHeight` is tested.  This is returning the `container.getHeight()` value, so the condition is failing and `scrollStop` is called immediately.

Have you got any idea when the scrollheight is coming back as this, even if I am literally at the top of the window?

**Comment by b8ne** [comment]
Update: Found to be an issue with `body: {overflow-x: hidden;}` which was swapping width and height variables of `scrollingElement`.
Not sure why this occurs, as my other site has the same style and zenscroll works.

**Comment by zengabor** [comment]
I am glad to read you could sort it out. If you share the page with me I can look into it, and maybe find a solution.

By the way, I am just curious: why do you do `zenscroll.toY(el.offsetTop, 1000)` instead of `zenscroll.to(el, 1000)`? If it's because of the offset, you can set it to 0 initially via `zenscroll.setup(null, 0)` or even `zenscroll.setup(1000, 0)` and then just `zenscroll.to(el)`

**Comment by adleviton** [comment]
Thanks @b8ne , this lead me to find that having body { height: 100%; } was preventing zenscroll from working, for me at least. Sorry if I missed that in the instructions somewhere.
