### ISSUE TITLE
Consider changing the way automatic smoothing works

### ISSUE THREAD

**Issue by cannuk** [zengabor/zenscroll#39]
The current implementation for turning off automatic smoothing makes it hard to use in test environments and other setups. In both tests and in my application, I don't want to have to set a global variable at the window level to turn off this feature. Is there any chance of changing this to be an opt in behavior? Or at the very least maybe the ability to opt out when calling `setup`?

**Comment by zengabor** [comment]
I see what you need but unfortunately it would be quite hard to change the default auto opt-in (which was implemented this way because I thought most people want this by default).

So why not fork the code? Only a single line needs to be changed: https://github.com/zengabor/zenscroll/blob/dist/zenscroll.js#L258
