### ISSUE TITLE
Zenscroll not working in Chrome

### ISSUE THREAD

**Issue by RossThorn** [zengabor/zenscroll#49]
I'm using zenscroll in my website and it works perfectly in firefox. However, when I use it in chrome it doesn't work.

This is the button I attach it to, with only some styling attached to .portbutton and .button-text.

```<a class ="smooth-containter" href="#portfolio">
      <div class="portbutton">
        <span class="button-text">See My Work<i class="fa fa-chevron-down pulse" aria-hidden="true"></i>
        </span>
      </div>
    </a>```

**Comment by zengabor** [comment]
Could you find a solution?

**Comment by RossThorn** [comment]
Thanks for responding! 

No I wasn't able to find one.

I use it on [my website](https://rossthorn.github.io). Any ideas?

**Comment by obscuredetour** [comment]
I think I found a solution to Zenscroll not working in Chrome.

For whatever reason the issue seems to be the CSS property `scroll-behavior: smooth`. Omitting this CSS property in Chrome allows Zenscroll to function properly. 

I was unable to test the fix on @RossThorn's website due to a 404 on the zenscroll-min.js resource.

In any rate, this omission did fix the issue for me and the [website](http://develop--bmkc.netlify.com)* I am developing. 
*WIP - see the 'Get Started' and 'News' links

I am not sure of the ramifications of this omission, perhaps @zengabor can shed some light into this.

**Comment by RossThorn** [comment]
Thanks @obscuredetour! I'll try your solution and let you know!

**Comment by RossThorn** [comment]
Omitting the `scroll-behavior: smooth` doesn't work for me in Chrome and actually makes it not work in Firefox as well.

**Comment by zengabor** [comment]
Hi @RossThorn, I would like to look into this issue. Can this issue reproduced somewhere?

**Comment by RossThorn** [comment]
Hi @zengabor! I have just redesigned my website from scratch and haven't gotten around to reimplementing zenscroll. But I will let you know when I do and if the problem still shows up!
