### ISSUE TITLE
Easing

### ISSUE THREAD

**Issue by stratboy** [zengabor/zenscroll#64]
Hi, thank you for your code. Though, zenscroll lacks a key feature that can make it stand above the good old jquery.animate: easing functions. This is basically the only thing jquery.animate lacks, so, I'll choose zenscroll when it will implement ;)
For example, [jump.js](http://callmecavs.com/jump.js/) is a delicious scroll engine which do have easing functions. but it's made for modern js workflows, es6 traspile and the like.. not always good.
So, add easings and you'll be the King! ;) 🗡

**Comment by zengabor** [comment]
Thanks for the suggestions. Actually, Zenscroll does have easing, both at the start and the end of the scrolling. That's why it's so smooth. But it's true that it's not configurable: it's always the same easing algorythm. I chose this delibarately. There are other libraries that support easing configurability, see for example this: https://github.com/cferdinandi/smooth-scroll#easing-options

**Comment by stratboy** [comment]
I really like smooth-scroll and I contributed a bit to it, suggesting a way to implement adaptive scroll timing, now up and running (maybe you should too ;)), but I personally don't like too much it's approach of accepting anchors as targets on the constructor, instead of the real target objects like zenscroll (and jquery.animate) do.
