### ISSUE TITLE
Scrolling works on second anchor click only.

### ISSUE THREAD

**Issue by JayBox325** [zengabor/zenscroll#68]
Hi,

Firstly, really nice library. Such an easy implementation of a common feature. 👍🏼

But I'm finding that when I click an anchor link the first time, it jumps with the browser's expected behaviour. But, when I click the same anchor a second time, it works with the smooth scrolling.

I haven't been able to see anythig about any special implementation that I'd have needed so here is my project markup:

**Javascript:**

     const defaultDuration = 777 // ms
     const edgeOffset = 0 // px
     zenscroll.setup(defaultDuration, edgeOffset)

**HTML**

    <a href="#nextWorkshop" class="tailwind-stuff-here">Click</a>

**Comment by zengabor** [comment]
Hi, can you give me a page where this is reproducable? Would be great to fix it.

**Comment by JayBox325** [comment]
I've invited you to a project. Just need to npm i or yarn to get up and running. I haven't been able to reproduce it on Codepen. I have set up a `feature/scroll-issue` branch, but I'll make it as easy as possible.

Just run `npm i` or `yarn` to get set up then run `npm start`.

The scroll element is the "Next workshop" link in the hero section, click it once and it jumps, click it a second time and it scrolls beautifully.

The scroller JS file is located in `_src/scripts/modules/smoothScroll.js` and that HTML is located in `_src/html/index.njk`.

**Comment by JayBox325** [comment]
@zengabor, I have pushed this project to a development server so you can witness it, but I'm still not sure what's causing the delay.

**Comment by kaytuca** [comment]
I want to offer some information that may help with having to double click the anchor to get zenscroll to scroll (or when it won't scroll at all). 

-- sometimes caused by HTML errors before the anchor. 
Errors that have caused either a need to double-click or no scrolling include:
*an "id" missing one or both of the quotation marks
*a missing "id"
*a duplicated "id"
*a typo such as a hidden tab inside an id name (hence changing the name)
These errors can be traced WITH zenscroll because scrolling works on a page from the top down and then going back up UNTIL zenscroll encounters the error going down the page, and then fails to go up afterwards. 

-- often caused by the anchor being near the very bottom of the webpage. 
* I found that when I had SHORT webpages, I often ran into the need to double click on an anchor  at the bottom of the page to get zenscroll to  scroll back up the webpage. With experimentation, I learned that when I was using my mouse to scroll down to the bottom of the webpage and hit the bottom of the page "hard" while scrolling with my mouse, almost always I had to double click after that to get to move up the page. Similarly, if the webpage wasn't very long, if I was using zenscroll to scroll to an anchor at the bottom, the scroller seemed to "hit the bottom of the page" hard and I needed to double-click on some (though not all) anchors near the bottom of the page for zenscroll to scroll back up the page (though usually not all the anchors.... just some!). 
* I have also learned that if I stopped scrolling with my mouse JUST BEFORE I hit the very bottom of a webpage in a browser, the anchors that needed double clicks if I "hit hard" the bottom of the page now work just find  to scroll back up on one click. 
* I also discovered that by putting a large blank margin near the bottom of my webpages, the anchors at the bottom of my pages work without needing to double-click.... there is enough room at the bottom of the page to prevent "hard mouse scrolling hitting the bottom of the browser window" and for zenscroll to calculate the bottom of the page.
* I believe this double-clicking issue is related to the following report on calculation of the bottom of the page, https://github.com/zengabor/zenscroll/issues/56, because having a "large bottom margin" moves the anchor far enough away from the bottom of the page so the miscalculation will no longer affect the anchor.  I am using roughly a 2" margin now on my webpages.

Hope this information helps. 

The solution until the bottom of the page calculation is corrected:  use a large margin on the bottom of my pages (2" or so). That workaround resolved ALL my needs to double-click anchors for which I could not find an HTML programming error.

**Comment by yann-catlinn** [comment]
I've had the same problem and I found a solution that works for me pretty good!
[https://stackoverflow.com/questions/60952725/anchor-in-nuxt-component-not-working-on-same-page-the-anchor-is-included-on](url)

Here is the code that I included in the router.scrollBehavior.js 

```
export default async function (to, from, savedPosition) {


if (savedPosition) {
    console.log("SAVED POSITION");
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve({
          selector: savedPosition
        });
      }, 600);
    });
    // not working consistently due to render
    //return savedPosition;
}
else if (to.hash) {
    console.log("HASH");
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({
        selector: to.hash
      });
    }, 600);
  });
}
else {
    console.log("NORMAL");
    return { x: 0, y: 0 };
}}
```

**Comment by zengabor** [comment]
It's possible that [`v5`](https://github.com/zengabor/zenscroll/blob/zengabor-v5-0-0/zenscroll5.js). If not, feel free to reopen
